# 定义 stages
stages:
  - push
variables:
  DEV_IMAGE_NAME: ${CI_PROJECT_PATH}/image

# 推送镜像到线下代码仓库
push_image:
  stage: push
  script:
    - docker build -t ${DEV_IMAGE_NAME}:${CI_COMMIT_SHA} .
    - sh /data/gitlab/bin/push.sh ${DEV_IMAGE_NAME}:${CI_COMMIT_SHA} dev
  only:
    - master
  tags:
    - CI